(function(){
  async function loadUpdatedLogo(){
    try{
      const parts=['/assets/logo-new.part0.b64','/assets/logo-new.part1.b64','/assets/logo-new.part2.b64','/assets/logo-new.part3.b64','/assets/logo-new.part4.b64'];
      const text=(await Promise.all(parts.map(p=>fetch(p,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(p);return r.text()})))).join('').replace(/\s+/g,'');
      const bin=atob(text),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);
      const url=URL.createObjectURL(new Blob([bytes],{type:'image/jpeg'}));
      document.querySelectorAll('img.logo,img.splash-logo').forEach(img=>{img.src=url;img.style.opacity='1'});window.AMIT_TOUCH_LOGO_URL=url;
    }catch(e){console.error('AMIT TOUCH logo failed',e)}
  }
  loadUpdatedLogo();
  const brand=document.createElement('script');brand.src='/brand-assets.js?v=3';document.head.appendChild(brand);
  const ui=document.createElement('style');
  ui.textContent=`html,body{background:linear-gradient(180deg,#fffaf6,#f8f1eb)!important}.app{max-width:430px!important;padding:12px 14px 104px!important}.glass{background:linear-gradient(145deg,rgba(255,255,255,.80),rgba(255,255,255,.34))!important;border:1px solid rgba(255,255,255,.94)!important;box-shadow:0 12px 30px rgba(55,69,65,.08),inset 0 1px 0 #fff!important;backdrop-filter:blur(24px) saturate(145%)!important;-webkit-backdrop-filter:blur(24px) saturate(145%)!important}.card,.booking,.notice{border-radius:16px!important}.primary{min-height:54px!important;border-radius:13px!important;background:linear-gradient(135deg,#34766f,#235d58)!important;box-shadow:0 9px 22px rgba(34,91,85,.18)!important}.admin-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.admin-actions button{min-height:42px;border-radius:12px;font-size:11px}.admin-approve{border:0;background:#2f716b;color:#fff}.admin-reject{border:1px solid rgba(176,105,94,.18);background:#fff4f1;color:#a76459}.admin-approve:disabled,.admin-reject:disabled{opacity:.55;pointer-events:none}`;
  document.head.appendChild(ui);
  const ADMIN_SERVICES={gel:{id:'gel',name:'לק ג׳ל',price:150,minutes:60},fill:{id:'fill',name:'מילוי',price:200,minutes:90},new:{id:'new',name:'בנייה חדשה',price:250,minutes:120},remove:{id:'remove',name:'הסרה בלבד',price:25,minutes:30}};
  const notice=(message,title='כמעט שם')=>typeof window.amitNotice==='function'?window.amitNotice(message,title):window.alert(message);
  function cleanPhone(value){let phone=String(value||'').replace(/\D/g,'');if(phone.startsWith('972')&&phone.length>=11)phone='0'+phone.slice(3);return phone;}
  async function resolveCustomer(fullName,phone){const lookup=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName,phone})});if(lookup.ok){const data=await lookup.json();if(data.role==='admin')throw new Error('ADMIN_NOT_CUSTOMER');return data.customer;}if(lookup.status!==404)throw new Error('CUSTOMER_LOOKUP_FAILED');const parts=fullName.replace(/\s+/g,' ').trim().split(' ');const firstName=parts.shift()||'';const lastName=parts.join(' ');if(!firstName||!lastName)throw new Error('FULL_NAME_REQUIRED');const create=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName,lastName,phone,birthDate:null})});const data=await create.json();if(!create.ok)throw new Error(data.error||'CUSTOMER_CREATE_FAILED');return data.customer;}
  function adminShell(){return `<div style="display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:10px 0 16px"><button class="primary" style="margin:0" onclick="openAdminBooking()">＋ קביעת תור</button><button class="glass card" style="margin:0;border:0;font-weight:600" onclick="renderAdmin()">↻ רענון</button></div>`;}
  window.openAdminBooking=function(){const target=document.getElementById('adminBody');if(!target)return;target.innerHTML=`${adminShell()}<div class="glass card"><h3 style="margin-top:0">קביעת תור ידנית</h3><input id="adminCustomerName" class="field" placeholder="שם מלא"><input id="adminCustomerPhone" class="field" inputmode="tel" placeholder="מספר נייד"><select id="adminService" class="field"><option value="gel">לק ג׳ל · ₪150 · שעה</option><option value="fill">מילוי · ₪200 · שעה וחצי</option><option value="new">בנייה חדשה · ₪250 · שעתיים</option><option value="remove">הסרה בלבד · ₪25</option></select><input id="adminDate" class="field" type="date"><input id="adminTime" class="field" type="time" step="1800"><button class="primary" onclick="adminCreateBooking()">שמירת התור ביומן</button><button class="secondary" onclick="renderAdmin()">ביטול וחזרה</button></div>`;};
  window.adminCreateBooking=async function(){const fullName=document.getElementById('adminCustomerName').value.replace(/\s+/g,' ').trim();const phone=cleanPhone(document.getElementById('adminCustomerPhone').value);const serviceId=document.getElementById('adminService').value;const date=document.getElementById('adminDate').value;const time=document.getElementById('adminTime').value;if(!fullName||phone.length<9||!date||!time)return notice('יש למלא שם מלא, נייד, שירות, תאריך ושעה');const svc=ADMIN_SERVICES[serviceId];try{const customer=await resolveCustomer(fullName,phone);const availability=await fetch(`/api/availability?date=${encodeURIComponent(date)}&minutes=${svc.minutes}`);const availabilityData=await availability.json();if(!availability.ok)throw new Error(availabilityData.error||'AVAILABILITY_FAILED');if(!availabilityData.slots.includes(time))return notice('השעה שבחרת אינה פנויה ביומן. בחרי שעה אחרת.');const response=await fetch('/api/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:customer.id,serviceCode:svc.id,service:svc.name,price:svc.price,date,time,minutes:svc.minutes,extra:'נקבע ידנית על ידי עמית',createdByAdmin:true})});const data=await response.json();if(!response.ok)throw new Error(data.error||'BOOKING_FAILED');notice('התור נשמר ואושר בהצלחה.','התור נקבע');await window.renderAdmin();}catch(error){console.error(error);notice('לא הצלחתי לשמור את התור. נסי שוב.');}};
  window.adminApproveAppointment=async function(id,button){if(!id)return notice('לא נמצא מזהה לתור הזה.','לא הצלחתי לאשר');const buttons=button?.closest('.admin-actions')?.querySelectorAll('button')||[];buttons.forEach(b=>b.disabled=true);try{const r=await fetch('/api/admin/appointments/'+encodeURIComponent(id)+'/approve',{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json'},body:'{}',cache:'no-store'});let d={};try{d=await r.json();}catch(_){}if(!r.ok)throw new Error(d.error||('HTTP_'+r.status));notice('התור אושר בהצלחה ונקבע ביומן.','התור אושר');await window.renderAdmin();}catch(e){console.error('Admin approval failed',e);buttons.forEach(b=>b.disabled=false);notice('לא הצלחתי לאשר את התור כרגע. נסי שוב.','לא הצלחתי לאשר');}};
  window.adminRejectAppointment=async function(id,button){const buttons=button?.closest('.admin-actions')?.querySelectorAll('button')||[];buttons.forEach(b=>b.disabled=true);try{const r=await fetch('/api/admin/appointments/'+encodeURIComponent(id)+'/reject',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:'בקשת התור לא אושרה על ידי עמית'}),cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'REJECTION_FAILED');notice('בקשת התור נדחתה.','הבקשה נדחתה');await window.renderAdmin();}catch(e){console.error(e);buttons.forEach(b=>b.disabled=false);notice('לא הצלחתי לדחות את הבקשה כרגע. נסי שוב.','לא הצלחתי לעדכן');}};
  window.adminCancelAppointment=async function(appointmentId,customerLabel){if(!appointmentId)return;try{const response=await fetch('/api/appointments/'+encodeURIComponent(appointmentId),{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:'בוטל על ידי עמית דרך ממשק המנהלת'})});const data=await response.json();if(!response.ok)throw new Error(data.error||'CANCELLATION_FAILED');notice('התור בוטל בהצלחה.','התור בוטל');await window.renderAdmin();}catch(error){console.error(error);notice('לא הצלחתי לבטל את התור. נסי שוב.','לא הצלחתי לבטל');}};
  function info(a){const c=a.customer||{};return{name:[c.first_name,c.last_name].filter(Boolean).join(' ')||'לקוחה',phone:c.phone||'',when:new Date(a.starts_at).toLocaleString('he-IL',{dateStyle:'short',timeStyle:'short'}),service:a.service_name||'',price:Number(a.total_price||0)};}
  window.renderAdmin=async function(){const target=document.getElementById('adminBody');if(!target)return;target.innerHTML=adminShell()+'<div class="card glass"><p class="subtitle">טוענת תורים…</p></div>';try{const response=await fetch('/api/admin/appointments',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'ADMIN_APPOINTMENTS_FAILED');const rows=(data.appointments||[]).filter(a=>a.status!=='cancelled');const pending=rows.filter(a=>a.status==='pending');const confirmed=rows.filter(a=>a.status==='confirmed');const pendingHtml=pending.length?'<div class="section-title">ממתינים לאישור</div>'+pending.map(a=>{const x=info(a);return `<div class="notice glass"><h3>${x.name}</h3><p>${x.service}<br>${x.when}<br>${x.phone}<br>₪${x.price}</p><div class="admin-actions"><button class="admin-approve" onclick="adminApproveAppointment('${a.id}',this)">אישור</button><button class="admin-reject" onclick="adminRejectAppointment('${a.id}',this)">דחייה</button></div></div>`}).join(''):'<div class="card glass"><p class="subtitle">אין בקשות שממתינות לאישור.</p></div>';const confirmedHtml=confirmed.length?'<div class="section-title">תורים מאושרים</div>'+confirmed.map(a=>{const x=info(a);return `<div class="notice glass"><h3>${x.name}</h3><p>${x.service}<br>${x.when}<br>${x.phone}<br>₪${x.price}</p><button class="cancel" onclick="adminCancelAppointment('${a.id}','${x.name.replace(/'/g,'&#39;')}')">ביטול התור</button></div>`}).join(''):'<div class="card glass"><p class="subtitle">אין כרגע תורים מאושרים.</p></div>';target.innerHTML=adminShell()+pendingHtml+confirmedHtml;}catch(error){console.error(error);target.innerHTML=adminShell()+'<div class="card glass">לא הצלחתי לטעון את נתוני הניהול</div>';}};
})();