(function(){
 const BUILD='20260820-gallery-ref-v1';
 const teal='#1f5d57', blush='#e5a39a';
 const imgs=[
  '/assets/home-hero-final.webp',
  '/assets/home-hero-transparent.webp',
  '/assets/home-hero-user-exact.webp',
  '/assets/home-hero.webp',
  '/assets/home-hero.png'
 ];
 const cats=['הכל','עיצובים','בנייה','מניקור'];
 function ensure(){
  let page=document.getElementById('gallery');
  if(!page){page=document.createElement('section');page.id='gallery';page.className='screen';document.querySelector('main.app')?.appendChild(page);}
  page.innerHTML=`<div class="gallery-shell">
    <div class="gallery-top"><button class="gallery-back" type="button" aria-label="חזרה">←</button><div class="gallery-title-wrap"><h1>גלריה</h1><div class="gallery-mini-sep"><i></i><span>✦</span><i></i></div></div><button class="gallery-profile" type="button" aria-label="פרופיל"><img src="/assets/home-icon-profile-top.svg?v=${BUILD}" alt=""></button></div>
    <div class="gallery-tabs">${cats.map((c,i)=>`<button type="button" class="gallery-tab${i===0?' active':''}" data-cat="${c}">${c}</button>`).join('')}</div>
    <div class="gallery-main">
      <div class="gallery-stage"><img class="gallery-main-img" src="${imgs[0]}?v=${BUILD}" alt="עיצוב ציפורניים"><button class="gallery-fav" type="button" aria-label="שמירה למועדפים"><img src="/assets/amit-touch-heart.svg?v=${BUILD}" alt=""></button><button class="gallery-arrow prev" type="button" aria-label="הקודם">‹</button><button class="gallery-arrow next" type="button" aria-label="הבא">›</button></div>
      <div class="gallery-dots">${imgs.map((_,i)=>`<button type="button" class="gallery-dot${i===0?' active':''}" data-i="${i}" aria-label="תמונה ${i+1}"></button>`).join('')}</div>
      <div class="gallery-thumbs">${imgs.map((src,i)=>`<button type="button" class="gallery-thumb${i===0?' active':''}" data-i="${i}"><img src="${src}?v=${BUILD}" alt=""></button>`).join('')}</div>
    </div>
    <div class="gallery-footer-copy"><div class="gallery-wide-sep"><i></i><span>✦</span><i></i></div><h2>כל עיצוב נוצר במיוחד בשבילך</h2><p class="handwriting" data-handwriting>כי מגיע לך טאץ׳ משלך</p><img class="gallery-footer-heart" src="/assets/amit-touch-heart.svg?v=${BUILD}" alt=""></div>
  </div>`;
  return page;
 }
 document.getElementById('amit-gallery-style')?.remove();const s=document.createElement('style');s.id='amit-gallery-style';s.textContent=`
 #gallery{position:fixed!important;inset:0!important;z-index:29!important;background:#fbf6f1!important;overflow-y:auto!important;overflow-x:hidden!important;scrollbar-width:none!important;-webkit-overflow-scrolling:touch!important;padding:0!important}#gallery::-webkit-scrollbar{display:none!important}
 #gallery .gallery-shell{width:min(430px,100%)!important;min-height:100dvh!important;margin:0 auto!important;padding:28px 24px 46px!important;background:radial-gradient(circle at 16% 4%,rgba(255,255,255,.98),transparent 32%),linear-gradient(180deg,#fffaf7 0%,#fbf4ef 100%)!important;color:${teal}!important;box-sizing:border-box!important}
 #gallery .gallery-top{display:grid!important;grid-template-columns:46px 1fr 46px!important;align-items:start!important;margin-top:max(4px,env(safe-area-inset-top))!important}.gallery-back,.gallery-profile{width:44px!important;height:44px!important;border:0!important;background:transparent!important;color:${teal}!important;padding:0!important;display:grid!important;place-items:center!important}.gallery-back{font-size:34px!important;font-weight:200!important}.gallery-profile img{width:32px!important;height:32px!important;object-fit:contain!important}.gallery-title-wrap{text-align:center!important}.gallery-title-wrap h1{margin:6px 0 5px!important;font-size:27px!important;line-height:1.1!important;font-weight:500!important;color:${teal}!important}.gallery-mini-sep,.gallery-wide-sep{display:flex!important;align-items:center!important;justify-content:center!important;gap:10px!important;color:${teal}!important}.gallery-mini-sep i{width:38px!important;height:1px!important;background:${blush}!important;opacity:.6!important}.gallery-mini-sep span{font-size:16px!important}.gallery-wide-sep{gap:12px!important}.gallery-wide-sep i{height:1px!important;flex:1!important;background:linear-gradient(90deg,transparent,${blush})!important;opacity:.65!important}.gallery-wide-sep i:last-child{transform:scaleX(-1)!important}.gallery-wide-sep span{font-size:18px!important}
 #gallery .gallery-tabs{display:grid!important;grid-template-columns:repeat(4,1fr)!important;gap:10px!important;margin:32px 0 30px!important}.gallery-tab{height:48px!important;border:1px solid rgba(31,93,87,.13)!important;border-radius:26px!important;background:rgba(255,255,255,.28)!important;color:${teal}!important;font-size:16px!important;font-weight:400!important;box-shadow:0 4px 14px rgba(71,50,42,.035)!important}.gallery-tab.active{background:linear-gradient(135deg,#f3d5cf,#f6e1dc)!important;border-color:transparent!important}
 #gallery .gallery-stage{position:relative!important;width:100%!important;aspect-ratio:1/1.06!important;border-radius:24px!important;overflow:visible!important;margin:0 auto!important}.gallery-main-img{width:100%!important;height:100%!important;border-radius:24px!important;object-fit:cover!important;display:block!important}.gallery-fav{position:absolute!important;top:18px!important;left:18px!important;width:46px!important;height:46px!important;border:0!important;border-radius:50%!important;background:${teal}!important;display:grid!important;place-items:center!important;box-shadow:0 6px 16px rgba(31,93,87,.18)!important}.gallery-fav img{width:26px!important;height:26px!important;filter:brightness(0) invert(1)!important}.gallery-fav.saved{background:#f0cbc5!important}.gallery-arrow{position:absolute!important;top:50%!important;transform:translateY(-50%)!important;width:58px!important;height:58px!important;border:0!important;border-radius:50%!important;background:#fffaf7!important;color:${teal}!important;font-size:40px!important;font-weight:200!important;box-shadow:0 10px 24px rgba(76,60,52,.12)!important;display:grid!important;place-items:center!important;padding-bottom:4px!important}.gallery-arrow.prev{left:-28px!important}.gallery-arrow.next{right:-28px!important}
 #gallery .gallery-dots{display:flex!important;justify-content:center!important;gap:13px!important;margin:18px 0 20px!important}.gallery-dot{width:9px!important;height:9px!important;min-width:9px!important;padding:0!important;border:0!important;border-radius:50%!important;background:#e8c8c2!important}.gallery-dot.active{background:${teal}!important}
 #gallery .gallery-thumbs{display:grid!important;grid-template-columns:repeat(5,1fr)!important;gap:9px!important}.gallery-thumb{padding:0!important;border:0!important;border-radius:14px!important;overflow:hidden!important;aspect-ratio:1/1!important;background:transparent!important;opacity:.72!important}.gallery-thumb img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}.gallery-thumb.active{opacity:1!important;box-shadow:0 0 0 2px rgba(31,93,87,.15)!important}
 #gallery .gallery-footer-copy{margin-top:44px!important;text-align:center!important}.gallery-footer-copy h2{margin:26px 0 13px!important;font-size:21px!important;line-height:1.45!important;font-weight:400!important;color:${teal}!important}.gallery-footer-copy p{margin:0!important;font-size:24px!important;line-height:1.3!important;color:#d78980!important}.gallery-footer-heart{width:33px!important;height:33px!important;margin:18px auto 0!important;display:block!important;filter:none!important}
 @media(max-width:370px){#gallery .gallery-shell{padding-left:20px!important;padding-right:20px!important}.gallery-arrow.prev{left:-20px!important}.gallery-arrow.next{right:-20px!important}.gallery-tabs{gap:7px!important}.gallery-tab{font-size:16px!important}}
 `;document.head.appendChild(s);
 let index=0;function setIndex(i){const page=document.getElementById('gallery');if(!page)return;index=(i+imgs.length)%imgs.length;const main=page.querySelector('.gallery-main-img');if(main)main.src=imgs[index]+`?v=${BUILD}`;page.querySelectorAll('.gallery-dot,.gallery-thumb').forEach(el=>el.classList.toggle('active',Number(el.dataset.i)===index));}
 function open(){const page=ensure();document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));page.classList.add('active');document.querySelector('.nav')?.classList.remove('show');page.scrollTop=0;}
 ensure();
 document.addEventListener('click',e=>{const page=document.getElementById('gallery');const t=e.target.closest('button');if(!t)return;if(t.classList.contains('gallery-back')){window.show?.('home');document.querySelector('.nav')?.classList.add('show');}else if(t.classList.contains('gallery-profile')){window.show?.('profile');document.querySelector('.nav')?.classList.add('show');}else if(t.classList.contains('gallery-arrow'))setIndex(index+(t.classList.contains('next')?1:-1));else if(t.classList.contains('gallery-dot')||t.classList.contains('gallery-thumb'))setIndex(Number(t.dataset.i));else if(t.classList.contains('gallery-fav'))t.classList.toggle('saved');else if(t.classList.contains('gallery-tab')){page?.querySelectorAll('.gallery-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');}}
 );
 document.addEventListener('click',e=>{const el=e.target.closest('button,a,[role="button"]');if(!el)return;if((el.textContent||'').trim()==='גלריה'){e.preventDefault();e.stopPropagation();open();}},true);
 window.gallery=open;window.openGallery=open;
})();