(function(){
 const BUILD='20260820-gallery-scroll-v5';
 const teal='#1f5d57';
 const imgs=[
  '/assets/WhatsApp%20Image%202026-08-20%20at%2014.44.29.jpeg',
  '/assets/WhatsApp%20Image%202026-08-15%20at%2020.58.05.jpeg',
  '/assets/WhatsApp%20Image%202026-08-20%20at%2014.44.28.jpeg',
  '/assets/WhatsApp%20Image%202026-08-20%20at%2014.44.29%20(1).jpeg',
  '/assets/WhatsApp%20Image%202026-08-20%20at%2014.45.51.jpeg',
  '/assets/WhatsApp%20Image%202026-08-20%20at%2014.45.52.jpeg'
 ];
 function currentUser(){try{return window.user||user||{}}catch(_){return{}}}
 function favoritesKey(){const u=currentUser();return 'amit-gallery-favorites-'+String(u.id||u.phone||'guest')}
 function loadFavorites(){try{const v=JSON.parse(localStorage.getItem(favoritesKey())||'[]');return new Set(Array.isArray(v)?v:[])}catch(_){return new Set()}}
 function saveFavorites(set){try{localStorage.setItem(favoritesKey(),JSON.stringify([...set]))}catch(_){}}
 let favorites=loadFavorites();
 function ensure(){
  let page=document.getElementById('gallery');
  if(!page){page=document.createElement('section');page.id='gallery';page.className='screen';document.querySelector('main.app')?.appendChild(page);}
  page.innerHTML=`<div class="gallery-shell">
   <div class="gallery-top"><span class="gallery-spacer" aria-hidden="true"></span><div class="gallery-title-wrap"><h1>גלריה</h1></div><button class="gallery-profile" type="button" aria-label="פרופיל"><img src="/assets/home-icon-profile-top.svg?v=${BUILD}" alt=""></button></div>
   <div class="gallery-main"><div class="gallery-stage"><img class="gallery-main-img" src="${imgs[0]}?v=${BUILD}" alt="עיצוב ציפורניים" draggable="false"><button class="gallery-fav" type="button" aria-label="שמירה למועדפים"><img src="/assets/amit-touch-heart.svg?v=${BUILD}" alt=""></button></div><div class="gallery-dots">${imgs.map((_,i)=>`<button type="button" class="gallery-dot${i===0?' active':''}" data-i="${i}" aria-label="תמונה ${i+1}"></button>`).join('')}</div><div class="gallery-thumbs">${imgs.map((src,i)=>`<button type="button" class="gallery-thumb${i===0?' active':''}" data-i="${i}"><img src="${src}?v=${BUILD}" alt=""></button>`).join('')}</div></div>
   <div class="gallery-footer-copy"><div class="gallery-wide-sep"></div><h2>כל עיצוב נוצר במיוחד בשבילך</h2><div class="gallery-hand-row"><p class="handwriting">כי מגיע לך טאץ׳ משלך</p><img class="gallery-footer-heart" src="/assets/amit-touch-heart.svg?v=${BUILD}" alt=""></div></div>
  </div>`;
  return page;
 }
 document.getElementById('amit-gallery-style')?.remove();
 const s=document.createElement('style');s.id='amit-gallery-style';s.textContent=`
 #gallery{position:fixed!important;inset:0!important;z-index:29!important;background:#fbf6f1!important;overflow-y:auto!important;overflow-x:hidden!important;scrollbar-width:none!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior-y:contain!important;touch-action:pan-y!important;padding:0!important;scroll-padding-bottom:180px!important}#gallery::-webkit-scrollbar{display:none!important}
 #gallery .gallery-shell{width:min(430px,100%)!important;min-height:calc(100dvh + 1px)!important;margin:0 auto!important;padding:28px 24px max(190px,calc(150px + env(safe-area-inset-bottom)))!important;background:radial-gradient(circle at 16% 4%,rgba(255,255,255,.98),transparent 32%),linear-gradient(180deg,#fffaf7 0%,#fbf4ef 100%)!important;color:${teal}!important;box-sizing:border-box!important}
 #gallery .gallery-top{display:grid!important;grid-template-columns:46px 1fr 46px!important;align-items:start!important;margin-top:max(4px,env(safe-area-inset-top))!important;margin-bottom:30px!important}.gallery-spacer{width:44px!important;height:44px!important}.gallery-profile{width:44px!important;height:44px!important;border:0!important;background:transparent!important;padding:0!important;display:grid!important;place-items:center!important}.gallery-profile img{width:32px!important;height:32px!important;object-fit:contain!important}.gallery-title-wrap{text-align:center!important}.gallery-title-wrap h1{margin:6px 0 0!important;font-size:27px!important;line-height:1.1!important;font-weight:500!important;color:${teal}!important}
 #gallery .gallery-stage{position:relative!important;width:100%!important;aspect-ratio:1/1.06!important;border-radius:24px!important;overflow:hidden!important;margin:0 auto!important;touch-action:pan-y!important;user-select:none!important}.gallery-main-img{width:100%!important;height:100%!important;border-radius:24px!important;object-fit:cover!important;display:block!important;pointer-events:none!important}.gallery-fav{position:absolute!important;top:18px!important;left:18px!important;width:46px!important;height:46px!important;border:1px solid rgba(31,93,87,.2)!important;border-radius:50%!important;background:rgba(255,255,255,.88)!important;display:grid!important;place-items:center!important;box-shadow:0 6px 16px rgba(31,93,87,.12)!important;z-index:2!important;transition:background .18s ease,border-color .18s ease!important}.gallery-fav img{width:26px!important;height:26px!important;filter:none!important}.gallery-fav.saved{background:${teal}!important;border-color:${teal}!important}.gallery-fav.saved img{filter:brightness(0) invert(1)!important}
 #gallery .gallery-dots{display:flex!important;justify-content:center!important;gap:13px!important;margin:18px 0 20px!important}.gallery-dot{width:9px!important;height:9px!important;min-width:9px!important;padding:0!important;border:0!important;border-radius:50%!important;background:#e8c8c2!important}.gallery-dot.active{background:${teal}!important}
 #gallery .gallery-thumbs{display:grid!important;grid-template-columns:repeat(6,1fr)!important;gap:7px!important}.gallery-thumb{padding:0!important;border:0!important;border-radius:12px!important;overflow:hidden!important;aspect-ratio:1/1!important;background:transparent!important;opacity:.68!important}.gallery-thumb img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}.gallery-thumb.active{opacity:1!important;box-shadow:0 0 0 2px rgba(31,93,87,.15)!important}
 #gallery .gallery-footer-copy{margin-top:44px!important;text-align:center!important}.gallery-wide-sep{height:1px!important;width:100%!important;margin:0!important;background:linear-gradient(90deg,rgba(47,113,107,0),rgba(47,113,107,.78),rgba(47,113,107,0))!important}.gallery-footer-copy h2{margin:26px 0 13px!important;font-size:21px!important;line-height:1.45!important;font-weight:400!important;color:${teal}!important}.gallery-hand-row{display:flex!important;direction:rtl!important;align-items:center!important;justify-content:center!important;gap:9px!important}.gallery-footer-copy p{margin:0!important;font-size:24px!important;line-height:1.3!important;color:#d78980!important}.gallery-footer-heart{width:31px!important;height:31px!important;display:block!important;flex:0 0 31px!important}
 @media(max-width:370px){#gallery .gallery-shell{padding-left:20px!important;padding-right:20px!important;padding-bottom:max(210px,calc(165px + env(safe-area-inset-bottom)))!important}.gallery-thumbs{gap:5px!important}}
 @media(max-height:760px){#gallery .gallery-shell{padding-bottom:max(220px,calc(175px + env(safe-area-inset-bottom)))!important}}
 `;document.head.appendChild(s);
 let index=0;
 function syncFavorite(){const page=document.getElementById('gallery');const btn=page?.querySelector('.gallery-fav');if(!btn)return;const saved=favorites.has(imgs[index]);btn.classList.toggle('saved',saved);btn.setAttribute('aria-pressed',String(saved));btn.setAttribute('aria-label',saved?'הסרה מהמועדפים':'שמירה למועדפים');}
 function setIndex(i){const page=document.getElementById('gallery');if(!page)return;index=(i+imgs.length)%imgs.length;const main=page.querySelector('.gallery-main-img');if(main)main.src=imgs[index]+`?v=${BUILD}`;page.querySelectorAll('.gallery-dot,.gallery-thumb').forEach(el=>el.classList.toggle('active',Number(el.dataset.i)===index));syncFavorite();}
 function open(){favorites=loadFavorites();const page=ensure();document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));page.classList.add('active');document.querySelector('.nav')?.classList.remove('show');page.scrollTop=0;bindSwipe(page);setIndex(index);}
 function bindSwipe(page){const stage=page.querySelector('.gallery-stage');if(!stage||stage.dataset.swipeBound)return;stage.dataset.swipeBound='1';let sx=0,sy=0,tracking=false;stage.addEventListener('pointerdown',e=>{if(e.target.closest('.gallery-fav'))return;tracking=true;sx=e.clientX;sy=e.clientY;});stage.addEventListener('pointerup',e=>{if(!tracking)return;tracking=false;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))setIndex(index+(dx<0?-1:1));});stage.addEventListener('pointercancel',()=>tracking=false);}
 ensure();bindSwipe(document.getElementById('gallery'));setIndex(0);
 document.addEventListener('click',e=>{const page=document.getElementById('gallery');const t=e.target.closest('button');if(!t)return;if(t.classList.contains('gallery-profile')){window.show?.('profile');document.querySelector('.nav')?.classList.add('show');}else if(t.classList.contains('gallery-dot')||t.classList.contains('gallery-thumb'))setIndex(Number(t.dataset.i));else if(t.classList.contains('gallery-fav')){const key=imgs[index];favorites.has(key)?favorites.delete(key):favorites.add(key);saveFavorites(favorites);syncFavorite();}});
 document.addEventListener('click',e=>{const el=e.target.closest('button,a,[role="button"]');if(!el)return;if((el.textContent||'').trim()==='גלריה'){e.preventDefault();e.stopPropagation();open();}},true);
 window.gallery=open;window.openGallery=open;
})();