(function(){
  const BUILD='20260816-home-hero-v5';
  const home=document.getElementById('home');if(!home)return;document.getElementById('amit-home-polish')?.remove();
  const style=document.createElement('style');style.id='amit-home-polish';style.textContent=`
  #home{padding:0 0 94px!important;margin:0!important;color:#07584f!important;overflow:visible!important;background:#fff9f5!important}
  #home .top{height:58px!important;display:grid!important;grid-template-columns:42px 1fr 42px!important;align-items:center!important;padding:0 4px!important;position:relative!important;z-index:8!important}#home .top b{font-size:0!important}#home .top .round{width:38px!important;height:38px!important;border:0!important;background-color:transparent!important;box-shadow:none!important;font-size:0!important;background-repeat:no-repeat!important;background-position:center!important;background-size:29px 29px!important;padding:0!important}#home .top .round:first-child{background-image:url('/assets/home-icon-menu.svg?v=${BUILD}')!important}#home .top .round:last-child{background-image:url('/assets/home-icon-profile-top.svg?v=${BUILD}')!important}
  #home .home-hero{padding:0!important;margin:0!important;position:relative!important}#home .home-hero>.logo{display:block!important;width:190px!important;height:auto!important;max-width:66vw!important;margin:-48px auto 0!important;position:relative!important;z-index:9!important;object-fit:contain!important}
  #home .hero-photo{height:306px!important;margin:-3px -15px 12px!important;border:0!important;border-radius:0!important;box-shadow:none!important;position:relative!important;overflow:hidden!important;background:#fff9f5 url('/assets/home-hero.png?v=${BUILD}') right center/auto 100% no-repeat!important}
  #home .hero-photo:before{display:none!important;content:none!important}#home .hero-photo:after{content:''!important;position:absolute!important;inset:0!important;background:linear-gradient(90deg,#fff9f5 0%,rgba(255,249,245,.99) 14%,rgba(255,249,245,.86) 27%,rgba(255,249,245,.30) 46%,rgba(255,249,245,0) 61%)!important;pointer-events:none!important}
  #home .hero-copy{position:absolute!important;left:24px!important;right:auto!important;top:88px!important;bottom:auto!important;width:158px!important;text-align:right!important;direction:rtl!important;color:#07584f!important;z-index:4!important}#home .hero-copy:before,#home .hero-copy:after{display:none!important;content:none!important}
  #home .hero-name{display:block!important;margin:0 0 5px!important;color:#07584f!important;font-family:Inter,sans-serif!important;font-size:21px!important;line-height:1.15!important;font-weight:500!important}
  #home .hero-welcome{display:block!important;margin:0 0 7px!important;color:#07584f!important;font-family:Inter,sans-serif!important;font-size:17px!important;line-height:1.2!important;font-weight:300!important}
  #home .hero-touch{display:block!important;margin:0!important;color:#e7a19b!important;font-family:var(--hand,'GveretLevin',cursive)!important;font-size:31px!important;line-height:1.05!important;font-weight:100!important;font-synthesis:none!important;white-space:nowrap!important}
  #home .home-heart{display:block!important;width:27px!important;height:27px!important;margin:18px auto 0!important;background:url('/assets/amit-touch-heart.svg?v=${BUILD}') center/contain no-repeat!important}
  #home .primary{display:flex!important;align-items:center!important;justify-content:center!important;gap:18px!important;width:88%!important;height:66px!important;padding:0!important;margin:-25px auto 26px!important;border:1px solid rgba(255,255,255,.9)!important;border-radius:34px!important;background:linear-gradient(90deg,rgba(245,205,195,.86),rgba(225,177,163,.84))!important;color:#fff!important;font-size:22px!important;font-weight:400!important;box-shadow:0 12px 25px rgba(179,112,94,.18),inset 0 0 18px rgba(255,255,255,.38)!important;position:relative!important;z-index:5!important}#home .primary .home-book-icon{width:31px!important;height:31px!important;filter:brightness(0) invert(1)!important}
  #home .section-title{display:flex!important;align-items:center!important;justify-content:center!important;gap:15px!important;margin:20px 0 16px!important;color:#07584f!important;font-size:18px!important;line-height:1!important;font-weight:500!important;text-align:center!important}#home .section-title:before,#home .section-title:after{content:''!important;height:1px!important;flex:1!important;background:#eadfd9!important}
  #home .quick-grid{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:10px!important;margin:0 2px 27px!important;direction:rtl!important}#home .quick{height:125px!important;min-height:125px!important;padding:16px 4px 11px!important;border-radius:14px!important;border:1px solid rgba(239,228,221,.9)!important;background:rgba(255,255,255,.72)!important;box-shadow:0 8px 18px rgba(83,55,43,.07)!important;color:#07584f!important}#home .quick span{display:block!important;width:58px!important;height:66px!important;margin:0 auto 7px!important;font-size:0!important;background-position:center!important;background-repeat:no-repeat!important;background-size:contain!important}#home .quick:nth-child(1) span{background-image:url('/assets/home-service-design.svg?v=${BUILD}')!important}#home .quick:nth-child(2) span{background-image:url('/assets/home-service-gel.svg?v=${BUILD}')!important}#home .quick:nth-child(3) span{background-image:url('/assets/home-service-pedicure.svg?v=${BUILD}')!important}#home .quick:nth-child(4) span{background-image:url('/assets/home-service-manicure.svg?v=${BUILD}')!important}#home .quick b{display:block!important;font-family:Inter,sans-serif!important;font-size:13px!important;line-height:1.2!important;font-weight:400!important;color:#07584f!important;text-align:center!important}
  #home .next-card{display:grid!important;grid-template-columns:62px minmax(0,1fr) 82px!important;align-items:center!important;gap:14px!important;min-height:104px!important;margin:0 1px 24px!important;padding:15px 18px!important;border-radius:17px!important;background:rgba(255,255,255,.74)!important;border:1px solid rgba(239,228,221,.92)!important;box-shadow:0 9px 20px rgba(83,55,43,.07)!important;direction:ltr!important}#home .checkdot{width:49px!important;height:49px!important;border-radius:50%!important;background:#f8dcd5!important;border:0!important;color:#111!important;font-size:25px!important;display:grid!important;place-items:center!important}#home .next-card>div:nth-child(2){direction:rtl!important;text-align:right!important;border-right:1px solid #e5d8d2!important;padding-right:18px!important}#home .next-card small{font-size:14px!important;line-height:1.4!important;color:#1d2625!important;font-weight:400!important}#home .next-card b{font-size:15px!important;line-height:1.45!important;color:#151c1b!important;font-weight:400!important}#home .next-card>div:last-child{direction:rtl!important;text-align:center!important;color:#07584f!important;font-size:13px!important}#home .date-big{font-size:25px!important;line-height:1.1!important;font-weight:400!important;color:#07584f!important}
  #home .spark,#home .star,#home .stars,#home .sparkle,#home .sparkles,#home [class*="spark"],#home [class*="star"]{display:none!important;visibility:hidden!important;opacity:0!important}
  `;document.head.appendChild(style);
  const logo=home.querySelector('.logo');if(logo)logo.src=`/assets/amitouch_logo_vector.png?v=${BUILD}`;
  function firstName(){try{if(typeof user!=='undefined'&&user)return user.firstName||String(user.name||'').trim().split(/\s+/)[0]||''}catch(_){}try{const raw=localStorage.getItem('user')||localStorage.getItem('amitUser')||sessionStorage.getItem('user');if(raw){const u=JSON.parse(raw);return u.firstName||String(u.name||'').trim().split(/\s+/)[0]||''}}catch(_){}return''}
  function refreshGreeting(){const e=home.querySelector('.hero-copy');if(!e)return;const n=firstName();e.innerHTML=`<span class="hero-name">${n||'שם פרטי'}</span><span class="hero-welcome">ברוכה הבאה</span><strong class="hero-touch">לטאץ׳ שלך</strong><span class="home-heart" aria-hidden="true"></span>`}refreshGreeting();new MutationObserver(()=>{if(home.classList.contains('active'))refreshGreeting()}).observe(home,{attributes:true,attributeFilter:['class']});
  const primary=home.querySelector('.primary');if(primary)primary.innerHTML=`<img class="home-book-icon" src="/assets/home-nav-appointments.svg?v=${BUILD}" alt=""><span>הזמיני תור</span>`;
  const titles=home.querySelectorAll('.section-title');if(titles[0])titles[0].textContent='השירותים שלי';if(titles[1])titles[1].textContent='הזמנה אחרונה';
  const labels=['עיצוב והסרת','ג׳ל לק','מניקור','בניית ציפורניים'];home.querySelectorAll('.quick').forEach((e,i)=>{const b=e.querySelector('b');if(b&&labels[i])b.textContent=labels[i]});
})();