(function(){
 const BUILD='20260819-bottom-nav-exact-centers-v11',SPRITE='/assets/ChatGPT%20Image%20Aug%2016%2C%202026%2C%2010_46_54%20AM.png',screens=['bookings','services','home','about','profile'],labels=['זימון תור','השירותים שלי','בית','אודות','הגדרות ופרטי משתמש'];
 document.getElementById('amit-bottom-nav-style')?.remove();const style=document.createElement('style');style.id='amit-bottom-nav-style';style.textContent=`
 #amitBottomNav{position:fixed!important;z-index:90!important;left:50%!important;transform:translateX(-50%)!important;bottom:max(8px,env(safe-area-inset-bottom))!important;width:min(382px,calc(100vw - 30px))!important;height:56px!important;display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;align-items:center!important;padding:2px 8px!important;border-radius:30px!important;border:1px solid rgba(255,255,255,.94)!important;background:linear-gradient(110deg,rgba(255,255,255,.57),rgba(249,232,228,.47),rgba(255,255,255,.5))!important;box-shadow:0 8px 20px rgba(188,116,105,.14),inset 0 1px 1px rgba(255,255,255,.98)!important;backdrop-filter:blur(22px) saturate(145%)!important;-webkit-backdrop-filter:blur(22px) saturate(145%)!important;direction:rtl!important;overflow:visible!important}
 #amitBottomNav[hidden]{display:none!important}#amitBottomNav button{position:relative!important;width:100%!important;height:50px!important;min-width:0!important;border:0!important;background:transparent!important;padding:0!important;margin:0!important;display:block!important;color:#07584f!important;overflow:visible!important}#amitBottomNav button:after{content:''!important;position:absolute!important;left:50%!important;transform:translateX(-50%)!important;bottom:0!important;width:6px!important;height:6px!important;border-radius:50%!important;background:rgba(116,143,138,.42)!important}
 #amitBottomNav .nav-sprite{display:block!important;width:28px!important;height:28px!important;background-image:url('${SPRITE}?v=${BUILD}')!important;background-size:500% auto!important;background-repeat:no-repeat!important;background-position-y:center!important;position:absolute!important;z-index:2!important;left:50%!important;top:20px!important;transform:translate(-50%,-50%)!important;margin:0!important}
 #amitBottomNav button.active{z-index:2!important}#amitBottomNav button.active:before{content:''!important;position:absolute!important;width:58px!important;height:58px!important;left:50%!important;top:20px!important;transform:translate(-50%,-50%)!important;border-radius:50%!important;border:1px solid rgba(255,255,255,.95)!important;background:radial-gradient(circle at 42% 30%,rgba(255,255,255,.8),rgba(249,198,192,.7) 48%,rgba(238,173,167,.5) 100%)!important;box-shadow:0 7px 17px rgba(203,116,106,.18),inset 0 1px 0 rgba(255,255,255,.98)!important;backdrop-filter:blur(18px)!important}#amitBottomNav button.active:after{width:29px!important;height:5px!important;border-radius:6px!important;bottom:-3px!important;background:#e88f89!important}#amitBottomNav button.active .nav-sprite{left:50%!important;top:20px!important;transform:translate(-50%,-50%)!important}.screen.active{padding-bottom:70px!important}`;document.head.appendChild(style);
 document.querySelectorAll('.nav').forEach(n=>n.style.setProperty('display','none','important'));document.getElementById('amitBottomNav')?.remove();const nav=document.createElement('nav');nav.id='amitBottomNav';nav.setAttribute('aria-label','ניווט ראשי');
 const pos=['100%','75%','50%','25%','0%'];screens.forEach((target,i)=>{const b=document.createElement('button');b.type='button';b.dataset.target=target;b.setAttribute('aria-label',labels[i]);b.innerHTML=`<span class="nav-sprite" style="background-position-x:${pos[i]}"></span>`;b.onclick=()=>{if(typeof window.show==='function')window.show(target);requestAnimationFrame(sync)};nav.appendChild(b)});document.body.appendChild(nav);
 function sync(){const id=document.querySelector('.screen.active')?.id||'';nav.hidden=!id||id==='login'||id==='register';[...nav.querySelectorAll('button')].forEach(b=>b.classList.toggle('active',b.dataset.target===id))}sync();new MutationObserver(sync).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});
})();