(function(){
 const BUILD='20260820-bottom-nav-scroll-v19';
 const items=[
  {key:'booking',active:'services',label:'זימון תור',icon:'/assets/%D7%96%D7%99%D7%9E%D7%95%D7%9F%20%D7%AA%D7%95%D7%A8.png'},
  {key:'gallery',active:'gallery',label:'גלריית עבודות',icon:'/assets/%D7%92%D7%9C%D7%A8%D7%99%D7%99%D7%94.png'},
  {key:'home',active:'home',label:'בית',icon:'/assets/%D7%91%D7%99%D7%AA.png'},
  {key:'about',active:'about',label:'אודות',icon:'/assets/%D7%90%D7%95%D7%93%D7%95%D7%AA.png'},
  {key:'profile',active:'profile',label:'פרופיל',icon:'/assets/%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9.png'}
 ];
 if(!document.getElementById('gallery')){const gallery=document.createElement('section');gallery.id='gallery';gallery.className='screen';gallery.innerHTML='<header class="top"><button class="round" type="button" onclick="show(\'home\')">‹</button><b>גלריית עבודות</b><button class="round" type="button" onclick="show(\'home\')">›</button></header><div id="galleryBody"></div>';document.querySelector('main.app')?.appendChild(gallery);}
 document.getElementById('amit-bottom-nav-style')?.remove();
 const style=document.createElement('style');style.id='amit-bottom-nav-style';style.textContent=`
 html,body{scrollbar-width:none!important;-ms-overflow-style:none!important}html::-webkit-scrollbar,body::-webkit-scrollbar,.screen::-webkit-scrollbar{display:none!important;width:0!important;height:0!important}.screen{scrollbar-width:none!important;-ms-overflow-style:none!important}.screen.active{padding-bottom:82px!important;box-sizing:border-box!important}.screen.active:not(.amit-needs-scroll){overflow-y:hidden!important}.screen.active.amit-needs-scroll{overflow-y:auto!important;overscroll-behavior-y:contain!important}
 #amitBottomNav{position:fixed!important;z-index:90!important;left:50%!important;transform:translateX(-50%)!important;bottom:max(16px,calc(env(safe-area-inset-bottom) + 8px))!important;width:min(382px,calc(100vw - 30px))!important;height:56px!important;display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;align-items:center!important;padding:2px 8px!important;border-radius:30px!important;border:1px solid rgba(255,255,255,.94)!important;background:linear-gradient(110deg,rgba(255,255,255,.58),rgba(249,232,228,.48),rgba(255,255,255,.52))!important;box-shadow:0 10px 24px rgba(188,116,105,.14),inset 0 1px 1px rgba(255,255,255,.98)!important;backdrop-filter:blur(24px) saturate(150%)!important;-webkit-backdrop-filter:blur(24px) saturate(150%)!important;direction:rtl!important;overflow:visible!important}#amitBottomNav[hidden]{display:none!important}
 #amitBottomNav .nav-glass-indicator{position:absolute!important;z-index:1!important;top:50%!important;left:0!important;width:52px!important;height:52px!important;border-radius:999px!important;border:1.5px solid rgba(255,255,255,.96)!important;background:linear-gradient(145deg,rgba(255,255,255,.62),rgba(255,241,239,.5) 28%,rgba(247,201,199,.54) 64%,rgba(236,164,161,.42))!important;box-shadow:0 8px 18px rgba(176,105,98,.17),inset 0 2px 2px rgba(255,255,255,1)!important;backdrop-filter:blur(20px) saturate(150%)!important;-webkit-backdrop-filter:blur(20px) saturate(150%)!important;transform:translate3d(var(--bubble-x,0px),-66%,0)!important;transition:transform .36s cubic-bezier(.22,.8,.24,1)!important;pointer-events:none!important;overflow:hidden!important;clip-path:circle(50% at 50% 50%)!important}
 #amitBottomNav button{position:relative!important;z-index:2!important;width:100%!important;height:50px!important;border:0!important;background:transparent!important;padding:0!important;margin:0!important;display:block!important;overflow:visible!important}#amitBottomNav button:after{content:''!important;position:absolute!important;left:50%!important;transform:translateX(-50%)!important;bottom:1px!important;width:6px!important;height:6px!important;border-radius:50%!important;background:rgba(116,143,138,.42)!important}#amitBottomNav .nav-icon{position:absolute!important;left:50%!important;top:20px!important;transform:translate(-50%,-50%)!important;width:27px!important;height:27px!important;object-fit:contain!important}#amitBottomNav button.active:after{width:29px!important;height:5px!important;border-radius:6px!important;bottom:-4px!important;background:#e88f89!important}`;document.head.appendChild(style);
 document.querySelectorAll('.nav').forEach(n=>n.style.setProperty('display','none','important'));document.getElementById('amitBottomNav')?.remove();const nav=document.createElement('nav');nav.id='amitBottomNav';nav.setAttribute('aria-label','ניווט ראשי');const bubble=document.createElement('span');bubble.className='nav-glass-indicator';nav.appendChild(bubble);
 function go(item){if(item.key==='booking'){if(typeof window.services==='function')window.services();else window.show?.('services');return}if(item.key==='gallery'){window.show?.('gallery');return}if(item.key==='profile'){if(typeof window.profile==='function')window.profile();else window.show?.('profile');return}window.show?.(item.key)}
 items.forEach(item=>{const b=document.createElement('button');b.type='button';b.dataset.key=item.key;b.dataset.active=item.active;b.setAttribute('aria-label',item.label);b.innerHTML=`<img class="nav-icon" src="${item.icon}?v=${BUILD}" alt="">`;b.onclick=()=>{go(item);requestAnimationFrame(()=>requestAnimationFrame(sync))};nav.appendChild(b)});document.body.appendChild(nav);
 function updateScroll(screen){if(!screen)return;screen.classList.remove('amit-needs-scroll');requestAnimationFrame(()=>{const available=Math.max(0,window.innerHeight-82);const needs=screen.scrollHeight>available+2;screen.classList.toggle('amit-needs-scroll',needs);if(!needs)screen.scrollTop=0;});}
 function sync(){const screen=document.querySelector('.screen.active'),id=screen?.id||'';nav.hidden=!id||id==='login'||id==='register';const buttons=[...nav.querySelectorAll('button')];buttons.forEach(b=>b.classList.toggle('active',b.dataset.active===id));const active=buttons.find(b=>b.dataset.active===id);if(active&&!nav.hidden){const nr=nav.getBoundingClientRect(),ar=active.getBoundingClientRect(),center=ar.left-nr.left+ar.width/2;nav.style.setProperty('--bubble-x',`${center-26}px`)}updateScroll(screen)}
 requestAnimationFrame(()=>requestAnimationFrame(sync));addEventListener('resize',()=>requestAnimationFrame(sync),{passive:true});new MutationObserver(()=>requestAnimationFrame(sync)).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
})();