import fs from 'fs';
const originalReadFileSync=fs.readFileSync.bind(fs);
fs.readFileSync=function patchedReadFileSync(path,...args){
  const result=originalReadFileSync(path,...args);
  const pathText=String(path||'');
  if(!pathText.endsWith('index.html'))return result;
  const isBuffer=Buffer.isBuffer(result);
  let html=isBuffer?result.toString('utf8'):String(result);
  const build='20260820-atomic-startup-session-v67';
  const finalLogo=`/assets/amitouch_logo_vector.png?v=${build}`;
  html=html.replaceAll('/assets/amit-touch-logo.svg',finalLogo).replaceAll('/assets/amit-touch-logo.webp?v=20260815-final-logo',finalLogo).replaceAll('/assets/amit-touch-logo.webp?v=20260815-final',finalLogo).replaceAll('/assets/amit-touch-logo.webp',finalLogo).replaceAll('/assets/amit-touch-logo.png',finalLogo).replaceAll('/assets/amit-touch-logo.jpg',finalLogo).replaceAll('/assets/Amit%20Touch_Logo.png?v=20260815-uploaded',finalLogo).replaceAll('/assets/Amit%20Touch_Logo.png?v=20260815-login-2',finalLogo).replaceAll('/assets/Amit%20Touch_Logo.png?v=20260815-login',finalLogo).replaceAll('/assets/Amit%20Touch_Logo.png',finalLogo);
  html=html.replace(/<div class="splash-tag">[\s\S]*?<\/div>/,`<div class="splash-tag"><span class="splash-tag-line">הטאץ׳ הקטן שעושה</span><span class="splash-tag-line">את כל ההבדל</span></div>`);
  html=html.replace(/<div class="splash-heart">[\s\S]*?<\/div>/,`<div class="splash-heart"><img src="/assets/amit-touch-heart.svg?v=${build}" alt=""></div>`);
  const criticalSplash=`<script>document.documentElement.classList.add('amit-booting');</script><style id="splash-critical">html.amit-booting,html.amit-booting body{overflow:hidden!important;background:#fbf5ef!important}html.amit-booting body>*:not(#splash){display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}#splash{display:flex!important;position:fixed!important;inset:0!important;opacity:1!important;visibility:visible!important;pointer-events:auto!important;z-index:2147483647!important;background:#fbf5ef!important}.splash-inner{width:min(430px,100%)!important;height:100%!important;padding:0 22px!important;display:flex!important;flex-direction:column!important;align-items:center!important;text-align:center!important}.splash-logo,.splash-brand-logo{display:block!important;width:min(335px,84vw)!important;max-height:43vh!important;object-fit:contain!important;margin:12.5vh auto 0!important}.splash-tag{display:flex!important;flex-direction:column!important;align-items:center!important;margin:36px 0 0!important;color:#285f5a!important;font-size:25px!important;line-height:1.55!important;direction:rtl!important}.splash-tag-line{display:block!important;white-space:nowrap!important}.splash-heart{display:block!important;width:42px!important;height:42px!important;margin:20px auto 0!important}.splash-heart img{width:100%!important;height:100%!important;object-fit:contain!important}.brush-stroke,.brush-handle{display:none!important}#splash.brand-done{opacity:0!important;visibility:hidden!important;pointer-events:none!important}</style>`;
  html=html.replace('</head>',criticalSplash+'</head>');
  html=html.replace("setTimeout(()=>document.getElementById('splash').classList.add('hide'),1600);","/* splash timing is controlled exclusively by preload */");
  const runtime=`<script>(function(){
    const build='${build}',logo='${finalLogo}',root=document.documentElement;
    function fixSplash(){document.querySelectorAll('img.logo,img.splash-logo,img.splash-brand-logo').forEach(i=>{if(i.getAttribute('src')!==logo)i.setAttribute('src',logo)});const tag=document.querySelector('#splash .splash-tag');if(tag)tag.innerHTML='<span class="splash-tag-line">הטאץ׳ הקטן שעושה</span><span class="splash-tag-line">את כל ההבדל</span>';}
    function waitForBrand(){if(window.__AMIT_BRAND_READY__)return Promise.resolve();return new Promise(resolve=>{const done=()=>resolve();window.addEventListener('amit:splash-ready',done,{once:true});setTimeout(resolve,7000)})}
    async function finishBoot(){try{await Promise.all([waitForBrand(),window.__AMIT_SESSION_READY__||Promise.resolve()]);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));}catch(_){}const splash=document.getElementById('splash');splash?.classList.add('brand-done','hide');setTimeout(()=>{root.classList.remove('amit-booting');document.body.style.overflow='';},360)}
    function loadSequential(files){let i=0;function next(){if(i>=files.length){finishBoot();return}const item=files[i++];document.querySelectorAll('script[data-amit="'+item[1]+'"]').forEach(x=>x.remove());const s=document.createElement('script');s.src=item[0]+'?v='+build;s.dataset.amit=item[1];s.async=false;s.onload=next;s.onerror=next;document.body.appendChild(s)}next()}
    function boot(){fixSplash();loadSequential([['/brand-assets.js','brand-assets'],['/splash-force-two-lines.js','splash-force-two-lines'],['/global-notice.js','global-notice'],['/app-db.js','app-db'],['/cancellation-policy.js','cancellation-policy'],['/login-polish.js','login'],['/login-runtime-fix.js','login-runtime-fix'],['/register-polish.js','register'],['/register-age-check.js','register-age'],['/register-notice.js','register-notice'],['/admin-login.js','admin'],['/admin-ui.js','admin-ui'],['/admin-announcements.js','admin-announcements'],['/home-polish.js','home'],['/home-hero-reference.js','home-hero-reference'],['/home-services-slider.js','home-services-slider'],['/home-appointments-section.js','home-appointments-section'],['/home-announcements.js','home-announcements'],['/customer-notifications.js','customer-notifications'],['/about-page.js','about-page'],['/profile-page.js','profile-page'],['/preference-switch-fix.js','preference-switch-fix'],['/services-page.js','services-page'],['/service-detail-reference.js','service-detail-reference'],['/locked-static-pages.js','locked-static-pages'],['/nav-polish.js','bottom-nav'],['/login-home-guard.js','login-home-guard'],['/booking-runtime-fix.js','booking-runtime-fix'],['/booking-direction-fix.js','booking-direction-fix'],['/reference-booking-upload.js','reference-booking-upload'],['/font-minimum-16.js','font-minimum-16'],['/post-font-layout-fix.js','post-font-layout-fix'],['/auth-visual-fix.js','auth-visual-fix'],['/booking-confirmation-polish.js','booking-confirmation-polish'],['/gallery-page.js','gallery-page'],['/booking-controller.js','booking-controller'],['/pwa-install-prompt.js','pwa-install-prompt'],['/responsive-runtime.js','responsive-runtime'],['/session-persistence.js','session-persistence']])}
    if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  })();</script>`;
  html=html.replace('</body>',runtime+'</body>');
  return isBuffer?Buffer.from(html,'utf8'):html;
};